MAX_LEN_RECIPE_NAME = 256
MAX_LEN_INGREDIENT_NAME = 128
MAX_LEN_MEASURE = 64
MAX_LEN_TAG = 32
MAX_AUTHOR_RECIPES = 3
MAXIMUM_WORD_LENGTH = 20
MAX_LEN_EMAIL = 254
MAX_LEN_USERNAME = 150

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32767
MIN_INGREDIENT_AMOUNT = 1

COOKING_TIME_FAST_MAX = 30
COOKING_TIME_MEDIUM_MAX = 60
