# Generated by Django 5.1.1 on 2026-07-02 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента должно быть больше 0')], verbose_name='Количество'),
        ),
    ]
