# Generated by Django 5.1.1 on 2026-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('subscriber', models.F('subscribed_to')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
